import {
  Film,
  Calendar,
  Clapperboard,
  Flame,
  Sparkles,
  Star,
  Filter,
  Tv,
  Clock,
} from "lucide-react";

// Definition of all TMDB and Managed Panels
export const PANELS = [
  // 1. Managed Cinema Catalog
  {
    id: "MANAGED",
    group: "MANAGED",
    label: "Cinema Catalog",
    subLabel: "Active Schedule",
    endpoint: "FilmZone Local / Cloud DB",
    description:
      "Cinema tickets & showtime schedule catalog synced with customer booking website",
    icon: Film,
    isTmdb: false,
    mediaType: "movie",
  },

  // 1b. Cinema Booking API Movies
  {
    id: "CINEMA_API",
    group: "MANAGED",
    label: "Cinema Movies",
    subLabel: "Movies from TMDB",
    endpoint: "Cinema Booking API",
    description:
      "Movies stored in the Cinema Booking API — import from TMDB, update status, delete.",
    icon: Clapperboard,
    isTmdb: false,
    mediaType: "movie",
  },

  // 1c. Cinema Booking API Showtimes
  {
    id: "CINEMA_SHOWTIMES",
    group: "MANAGED",
    label: "Cinema Showtimes",
    subLabel: "Showtimes for booking",
    endpoint: "Cinema Booking API",
    description:
      "Showtimes stored in the Cinema Booking API — schedule movies in halls and inspect seat availability.",
    icon: Clock,
    isTmdb: false,
    mediaType: "movie",
  },

  // 2. TMDB Movie Panels
  {
    id: "TMDB_UPCOMING",
    group: "MOVIES",
    label: "Upcoming Movies",
    subLabel: "Releasing Soon",
    endpoint: "/movie/upcoming",
    description:
      "All upcoming cinema releases and blockbusters worldwide from TMDB",
    icon: Calendar,
    isTmdb: true,
    mediaType: "movie",
  },
  {
    id: "TMDB_NOW_PLAYING",
    group: "MOVIES",
    label: "Now Playing",
    subLabel: "In Theatres",
    endpoint: "/movie/now_playing",
    description: "Movies currently showing in cinemas and theatres worldwide",
    icon: Clapperboard,
    isTmdb: true,
    mediaType: "movie",
  },
  {
    id: "TMDB_TRENDING_MOVIES",
    group: "MOVIES",
    label: "Trending Movies",
    subLabel: "Top Heat",
    endpoint: "/trending/movie/day",
    description: "Daily and weekly trending movies with high engagement",
    icon: Flame,
    isTmdb: true,
    mediaType: "movie",
  },
  {
    id: "TMDB_POPULAR_MOVIES",
    group: "MOVIES",
    label: "Popular Movies",
    subLabel: "Global Hits",
    endpoint: "/movie/popular",
    description: "Current most popular movies globally ranked by viewership",
    icon: Sparkles,
    isTmdb: true,
    mediaType: "movie",
  },
  {
    id: "TMDB_TOP_RATED_MOVIES",
    group: "MOVIES",
    label: "Top Rated Movies",
    subLabel: "Hall of Fame",
    endpoint: "/movie/top_rated",
    description:
      "All-time critically acclaimed masterpieces and highest-rated movies",
    icon: Star,
    isTmdb: true,
    mediaType: "movie",
  },
  {
    id: "TMDB_DISCOVER_MOVIES",
    group: "MOVIES",
    label: "Discover Movies",
    subLabel: "Custom Filter",
    endpoint: "/discover/movie",
    description:
      "Custom multi-criteria discover endpoint with live genre and sorting filters",
    icon: Filter,
    isTmdb: true,
    mediaType: "movie",
  },

  // 3. TMDB TV Panels
  {
    id: "TMDB_TRENDING_TV",
    group: "TV",
    label: "Trending TV Shows",
    subLabel: "Top Heat TV",
    endpoint: "/trending/tv/day",
    description: "Trending television and streaming shows right now",
    icon: Flame,
    isTmdb: true,
    mediaType: "tv",
  },
  {
    id: "TMDB_POPULAR_TV",
    group: "TV",
    label: "Popular TV Series",
    subLabel: "Global Binge",
    endpoint: "/tv/popular",
    description: "Most watched TV series, anime, and drama globally",
    icon: Tv,
    isTmdb: true,
    mediaType: "tv",
  },
  {
    id: "TMDB_TOP_RATED_TV",
    group: "TV",
    label: "Top Rated TV Series",
    subLabel: "Critically Acclaimed",
    endpoint: "/tv/top_rated",
    description: "Highest rated TV series and classic shows of all time",
    icon: Star,
    isTmdb: true,
    mediaType: "tv",
  },
  {
    id: "TMDB_ON_THE_AIR_TV",
    group: "TV",
    label: "On The Air TV",
    subLabel: "Currently Airing",
    endpoint: "/tv/on_the_air",
    description: "TV series airing new episodes within the next 7 days",
    icon: Sparkles,
    isTmdb: true,
    mediaType: "tv",
  },
  {
    id: "TMDB_DISCOVER_TV",
    group: "TV",
    label: "Discover TV Shows",
    subLabel: "Custom Filter",
    endpoint: "/discover/tv",
    description: "Explore all TV shows with custom genre and sort filters",
    icon: Filter,
    isTmdb: true,
    mediaType: "tv",
  },
];
